name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - caiobo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Token padrão do GitHub
          action: "upload"
          app_location: "."             # Onde está o código (pasta com package.json)
          output_location: "build"      # Onde ficam os arquivos prontos após build (React = build)
