name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - caiobo  # Altere para a branch correta, caso necessário

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Usando uma versão mais recente do Node.js

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          cd tccfront  # Alterar se necessário para o diretório correto
          npm install

      # Passo 4: Rodar o build
      - name: Run build
        run: |
          cd tccfront  # Alterar para o diretório correto
          npm run build  # Certifique-se de que o Vite esteja configurado corretamente

      # Passo 5: Deploy no Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: './tccfront'  # Diretório do código fonte
          output_location: './tccfront/dist'  # Diretório de saída da build
          # Se você não tiver uma API, pode deixar o api_location vazio
          api_location: '/tccfront/src/api'  
