name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      caiobo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - uses: actions/checkout@v2

      # Passo 2: Configurar Node.js (caso use React, Vue, etc.)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ou a versão que você está usando

      # Passo 3: Instalar dependências e rodar build
      - name: Install dependencies and build
        run: |
          cd tccfront  # Se o front-end está no diretório tccfront
          npm install
          npm run build

      # Passo 4: Deploy para Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: './tccfront'  # Local do seu app (front-end)
          output_location: './tccfront/build'  # Onde a build do seu app vai
          api_location: '/tccfront/src/api'  # Deixe em branco se não tiver uma API, ou defina o caminho da API se tiver
