name: React Deployment

on:
  push:
    branches: [caiobo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        path: 'tccfront'

    - name: Verify files
      run: |
        echo "Conteúdo de tccfront:"
        ls -la tccfront
        echo "Package.json existe?"
        test -f tccfront/package.json && echo "SIM" || echo "NÃO"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: 'tccfront/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: tccfront
      env:
        CI: true

    - name: Build
      run: npm run build
      working-directory: tccfront

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: tccfront/build